### ISSUE TITLE
Python lists have no shape attribute

### ISSUE THREAD

**Issue by Wigder** [kenlimmj/fightin-words#1]
On line 103, when calling np.empty(self.priors.shape[0]), this will raise an error if an informed prior (a Python list) is passed, since it is not internally converted to an np list before shape is invoked.

**Comment by Wigder** [comment]
Thanks for the quick response!

**Comment by kenlimmj** [comment]
Thanks for the bug! 

Note: If you're pulling this from Pip or Anaconda... give it (and me) a while to update there. It's been a while since I looked at Python and I need to remember how to re-deploy :)

**Comment by Wigder** [comment]
Just one question if you have some time to help:

I managed to run everything successfully and am getting an output. As you may be able to infer from my submission above, I am trying to perform a calculation with an informative prior. However, even in the example provided, I am struggling to understand how the output is coherent according to the paper. I must be either misinterpreting the output, or the paper itself.
What I mean by the above is - when I run the provided example, the output is:

`[('brown', -0.11159788992602564), ('donkey', -0.11159788992602564), ('fox', -0.11159788992602564), ('lazier', -0.11159788992602564), ('purple', -0.11159788992602564), ('quick', -0.11159788992602564), ('jumps', 0.04795579532980462), ('lazy', 0.04795579532980462), ('over', 0.04795579532980462), ('pig', 0.04795579532980462), ('the', 0.22827369129510436)]`

Given that a comparison is taking place between `l1` and `l2`, how can it be that "brown" and "purple" have the same scores, knowing that they belong to different classes and each word shows up exactly once in its respective class? My expectation is that "brown", showing up only on `l1`, would have a positive score that would be the absolute value of that of "purple".

I fear I might be grossly misinterpreting the output.

**Comment by Wigder** [comment]
I had a discussion with @jmhessel over at his version of the [implementation ](https://github.com/jmhessel/FightingWords/issues/3) and managed to solve the issue above, but only when using his implementation. I can't figure out still why I am getting such an abnormal output when running your code and I do believe it is a mistake on my end. Once again, thanks a lot for your support and feedback!
